services:
  sldl-web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    env_file:
      - .env
    environment:
      - Sldl__Username=${SLSK_USERNAME}
      - Sldl__Password=${SLSK_PASSWORD}
      - Sldl__DownloadPath=/app/downloads
      - Spotify__ClientId=${SPOTIFY_CLIENT_ID}
      - Spotify__ClientSecret=${SPOTIFY_CLIENT_SECRET}
